#!/usr/bin/env python3
"""Generate codex/<name>.toml and opencode/agents/<name>.md from agents/*.md and the contract skill.

With --check, write nothing; exit 1 if a committed generated file differs or is missing.
"""
import json
import sys
from pathlib import Path

# Codex model + reasoning effort per agent.
PINS = {
    "operator": ("gpt-6-luna", "low"),
    "researcher": ("gpt-6-sol", "medium"),
    "builder": ("gpt-6-sol", "medium"),
    "specialist": ("gpt-6.1-sol", "high"),
    "reviewer": ("gpt-6.1-sol", "high"),
}
# opencode model (provider/model#variant) per agent.
OPENCODE_PINS = {
    "operator": "github-copilot/claude-haiku-4.5",
    "researcher": "github-copilot/claude-sonnet-5.5#medium",
    "builder": "github-copilot/claude-sonnet-5.5#medium",
    "specialist": "github-copilot/claude-opus-5.5#high",
    "reviewer": "github-copilot/claude-opus-5.5#high",
}
# Source `tools:` names -> opencode permission actions.
TOOL_ACTIONS = {
    "Read": "read",
    "Edit": "edit",
    "Write": "edit",
    "Grep": "grep",
    "Glob": "glob",
    "Bash": "shell",
    "WebFetch": "webfetch",
    "WebSearch": "websearch",
}
READ_ONLY = {"researcher", "reviewer"}
DELIM = "'''"
ROOT = Path(__file__).resolve().parent.parent


def split(path):
    """Return (frontmatter dict of top-level scalar keys, body)."""
    parts = path.read_text(encoding="utf-8").split("---\n", 2)
    if len(parts) != 3 or parts[0].strip():
        sys.exit(f"{path}: missing frontmatter")
    meta = {}
    for line in parts[1].splitlines():
        key, sep, value = line.partition(":")
        if sep and not line[0].isspace():
            meta[key.strip()] = value.strip()
    return meta, parts[2].strip()


def rule(action, effect):
    return f'{{action: {json.dumps(action)}, resource: "*", effect: {json.dumps(effect)}}}'


def build():
    """Return {relative path: content} for every generated file."""
    _, contract = split(ROOT / "skills/contract/SKILL.md")
    contract = contract.removeprefix("# Contract").strip()
    files = {}
    for path in sorted((ROOT / "agents").glob("*.md")):
        meta, body = split(path)
        for key in ("name", "description"):
            if not meta.get(key):
                sys.exit(f"{path}: frontmatter is missing '{key}'")
        name = meta["name"]
        if name not in PINS or name not in OPENCODE_PINS:
            sys.exit(f"{path}: agent '{name}' is missing from PINS or OPENCODE_PINS")
        instructions = f"{body}\n\n## Contract\n\n{contract}\n"
        if DELIM in instructions:
            sys.exit(f"{path}: body or contract contains the TOML delimiter {DELIM}")
        model, effort = PINS[name]
        sandbox = "read-only" if name in READ_ONLY else "workspace-write"
        # json.dumps yields a valid TOML basic string for these single-line values.
        files[f"codex/{name}.toml"] = (
            "# GENERATED by scripts/build.py — do not edit\n"
            f"name = {json.dumps(name)}\n"
            f"description = {json.dumps(meta['description'], ensure_ascii=False)}\n"
            f"model = {json.dumps(model)}\n"
            f"model_reasoning_effort = {json.dumps(effort)}\n"
            f"sandbox_mode = {json.dumps(sandbox)}\n"
            f"developer_instructions = {DELIM}\n{instructions}{DELIM}\n"
        )
        if not meta.get("maxTurns", "").isdigit():
            sys.exit(f"{path}: frontmatter is missing an integer 'maxTurns'")
        actions = []
        for tool in (t.strip() for t in meta.get("tools", "").split(",") if t.strip()):
            if tool not in TOOL_ACTIONS:
                sys.exit(f"{path}: unknown tool '{tool}' (add it to TOOL_ACTIONS)")
            if TOOL_ACTIONS[tool] not in actions:
                actions.append(TOOL_ACTIONS[tool])
        rules = [rule("*", "deny")] + [rule(a, "allow") for a in actions]
        perms = "".join(f"  - {r}\n" for r in rules)
        # YAML flow mappings with JSON strings: no YAML library needed.
        files[f"opencode/agents/{name}.md"] = (
            "---\n"
            "# GENERATED by scripts/build.py — do not edit\n"
            f"description: {json.dumps(meta['description'], ensure_ascii=False)}\n"
            "mode: subagent\n"
            f"model: {json.dumps(OPENCODE_PINS[name])}\n"
            f"steps: {int(meta['maxTurns'])}\n"
            f"permissions:\n{perms}"
            f"---\n\n{instructions}"
        )
    return files


def main():
    files = build()
    if "--check" in sys.argv[1:]:
        bad = [
            rel for rel, text in files.items()
            if not (ROOT / rel).is_file() or (ROOT / rel).read_text(encoding="utf-8") != text
        ]
        for rel in bad:
            print(f"drift: {rel}")
        sys.exit(1 if bad else 0)
    for rel, text in files.items():
        (ROOT / rel).parent.mkdir(parents=True, exist_ok=True)
        (ROOT / rel).write_text(text, encoding="utf-8")
        print(f"wrote {rel}")


if __name__ == "__main__":
    main()
