#!/usr/bin/env python3
"""Generate codex/<name>.toml agent profiles from agents/*.md and the contract skill."""
import json
import sys
from pathlib import Path

# Codex model + reasoning effort per agent.
PINS = {
    "operator": ("gpt-6-luna", "low"),
    "researcher": ("gpt-6-sol", "medium"),
    "builder": ("gpt-6-sol", "medium"),
    "specialist": ("gpt-6.1-sol", "high"),
    "reviewer": ("gpt-6.1-sol", "high"),
}
READ_ONLY = {"researcher", "reviewer"}
DELIM = "'''"
ROOT = Path(__file__).resolve().parent.parent


def split(path):
    """Return (frontmatter dict of top-level scalar keys, body)."""
    parts = path.read_text(encoding="utf-8").split("---\n", 2)
    if len(parts) != 3 or parts[0].strip():
        sys.exit(f"{path}: missing frontmatter")
    meta = {}
    for line in parts[1].splitlines():
        key, sep, value = line.partition(":")
        if sep and not line[0].isspace():
            meta[key.strip()] = value.strip()
    return meta, parts[2].strip()


def main():
    _, contract = split(ROOT / "skills/contract/SKILL.md")
    contract = contract.removeprefix("# Contract").strip()
    out = ROOT / "codex"
    out.mkdir(exist_ok=True)
    for path in sorted((ROOT / "agents").glob("*.md")):
        meta, body = split(path)
        for key in ("name", "description"):
            if not meta.get(key):
                sys.exit(f"{path}: frontmatter is missing '{key}'")
        name = meta["name"]
        if name not in PINS:
            sys.exit(f"{path}: agent '{name}' is missing from PINS")
        instructions = f"{body}\n\n## Contract\n\n{contract}\n"
        if DELIM in instructions:
            sys.exit(f"{path}: body or contract contains the TOML delimiter {DELIM}")
        model, effort = PINS[name]
        sandbox = "read-only" if name in READ_ONLY else "workspace-write"
        # json.dumps yields a valid TOML basic string for these single-line values.
        (out / f"{name}.toml").write_text(
            "# GENERATED by scripts/build-codex.py — do not edit\n"
            f"name = {json.dumps(name)}\n"
            f"description = {json.dumps(meta['description'], ensure_ascii=False)}\n"
            f"model = {json.dumps(model)}\n"
            f"model_reasoning_effort = {json.dumps(effort)}\n"
            f"sandbox_mode = {json.dumps(sandbox)}\n"
            f"developer_instructions = {DELIM}\n{instructions}{DELIM}\n",
            encoding="utf-8",
        )
        print(f"wrote codex/{name}.toml")


if __name__ == "__main__":
    main()
